---
title: "Kaggle House prize prediction"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
library(knitr)
require(cowplot)
```

```{r}
setwd("D:/Kaggle/House Prices Advanced Regression Techniques")
```

```{r}
train <- fread("train.csv", stringsAsFactors = TRUE)
test <- fread("test.csv", stringsAsFactors = TRUE)
```

```{r}
kable(head(train))
```

```{r}
train_nulls <- as.data.frame(colSums(is.na(train)))#as.data.frame(sapply(X = train, FUN = function(x) sum(is.na(x))))
train_nulls <- add_rownames(train_nulls, "Column")
colnames(train_nulls)[2] <- "nulls"
train_nulls$notNulls = nrow(train) - train_nulls$nulls
```

```{r}
train_nulls %>%
  filter(nulls > 0) %>%
  gather("null_flag", "count", -Column) %>%
  ggplot(aes(x = Column, y = count, fill = null_flag)) +
  geom_bar(stat = "identity",position = "fill") +
  theme(legend.position = "bottom") +
  coord_flip()
```

```{r}
# Converting subclass to factor
train$MSSubClass = as.factor(train$MSSubClass)
```

```{r}
# Visualizing sale price vs MsSubClass
ggplot(train, aes(x = MSSubClass, y = SalePrice)) +
  geom_boxplot()
```

```{r}
# visualize number of observation for each category
ggplot(train, aes(x = MSSubClass, fill = MSSubClass)) +
  geom_bar() +
  theme(legend.position =  "none")
```

```{r}
# visualize number of observation for each category
ggplot(train, aes(x = MSZoning)) +
  geom_bar()
```

```{r}
# Visualizing sale price vs MsSubClass
ggplot(train, aes(x = MSZoning, y = SalePrice)) +
  geom_boxplot()
```

```{r}

plot1 <- ggplot(train, aes(x = LotFrontage)) +
            geom_histogram(binwidth = 10) 

# Visualizing sale price vs LotFrontage
plot2 <- ggplot(train, aes(x = LotFrontage, y = SalePrice)) +
          geom_point() +
          geom_smooth(method = "lm") 

plot_grid(plot1, plot2, align='h')

```
```{r}
ggplot(train, aes(x =log( LotArea), y = SalePrice)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
# Strong relation ship between lot area and sale price
# Creating new feature for prize per square feet
train$psf <- train$SalePrice / train$LotArea
```

```{r}
train %>%
  group_by(Street) %>%
  summarise(count = n())
```

```{r}
# Too less values for Grvl. We can ignore that, but Let's first check box-plot if gravel can explain outliers?
ggplot(train, aes(x = Street, y = psf)) +
  geom_violin(fill = "red")
```

```{r}
train %>%
  group_by(Alley) %>%
  summarise(count = n())
```

```{r}
# Too many null values , but here NA means no alley access, can be good feature. Let's change value for that.
train[is.na(Alley)]$Alley = "No"
```

```{r}
# Too less values for Grvl. We can ignore that, but Let's first check box-plot if gravel can explain outliers?
ggplot(train, aes(x = Alley, y = psf, fill = Alley)) +
  geom_boxplot()
```

```{r}
train %>%
  group_by(LotShape) %>%
  summarise(count = n(),
            avg = mean(psf))
```

```{r}
# IR3 should have least prize, Reg highest in my opinion. Let's check
ggplot(train, aes(x = LotShape, y = psf, fill = LotShape)) +
  geom_boxplot()
```

```{r}
train %>%
  group_by(LandContour) %>%
  summarise(count = n(),
            avg = mean(psf))
```

```{r}
train %>%
  group_by(Utilities) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(count), desc(avg))
# Conclusion : We can ignore this variable.
```

```{r}
train %>%
  group_by(LotConfig) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(count), desc(avg))
# Conclusion : Hmmm...
```

```{r}
train %>%
  group_by(LandSlope) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(count), desc(avg))
# Conclusion : Nice One!! Speically we can penalize Sev slopes
```

```{r}
train %>%
  group_by(Neighborhood) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(count), desc(avg))
```

```{r}
ggplot(train, aes(x = Neighborhood, y = psf, fill = Neighborhood)) +
  geom_boxplot() +
  coord_flip() +
  theme(legend.position = "none")
# Conclustion : Definetely a differentiator
```

```{r}
train %>%
  group_by(Condition1) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(avg), desc(count))
# Conclustion : People don't like building adjacent to rail roads or streets.
```

```{r}
train %>%
  group_by(Condition2) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(avg), desc(count))
# Need to mix it with condition 1 to get better result
```

```{r}
train %>%
  group_by(BldgType) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(avg), desc(count)) 
# Conclusion : Superb Feature
```

```{r}
train %>%
  group_by(HouseStyle) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(avg), desc(count)) 
```

```{r}
ggplot(train, aes(x = HouseStyle, y = psf, fill = HouseStyle)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclusion : 2 story getting premium prize
```

```{r}
train$OverallQual = as.factor(train$OverallQual)
train %>%
  group_by(OverallQual) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(avg), desc(count)) 
```

```{r}
train %>%
  group_by(OverallQual) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  ggplot(aes(x = OverallQual, y = count, fill = OverallQual)) +
    geom_bar(stat = "identity") +
    theme(legend.position = "none")
```

```{r}
train %>%
  ggplot(aes(x = OverallQual, y = psf, fill = OverallQual)) +
    geom_boxplot() +
    theme(legend.position = "none")
# Definetly a decider. Possibaly most important feature
```

```{r}
train$OverallCond = as.factor(train$OverallCond)
train %>%
  group_by(OverallCond) %>%
  summarise(count = n(),
            avg = mean(psf)) %>%
  arrange(desc(avg), desc(count)) 
```

```{r}
train$OverallCond = as.factor(train$OverallCond)
train %>%
  ggplot(aes(x = OverallCond, y = psf, fill = OverallCond)) +
    geom_boxplot() +
    theme(legend.position = "none")
#Conclusion : Not quite impressive.
```

```{r}
# Again interesting feature : YearBuilt: Original construction date
train %>%
  ggplot(aes(x = YearBuilt)) +
  geom_histogram(binwidth = 5)
```

```{r}
max(train$YearBuilt)
```

```{r}
train %>%
  ggplot(aes(x = YearBuilt, y = psf)) +
    geom_jitter(color = "red", alpha = 0.3)
#Conclusion : Definetly latest home taking more prize. We can define new continous variable HouseAge
```

```{r}
# YearRemodAdd: Remodel date (same as construction date if no remodeling or additions)
# So let's first find out house is remodeled or not
train %>%
  mutate(remodel_flag = ifelse(YearBuilt == YearRemodAdd, "N", "Y")) %>%
  group_by(remodel_flag) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))

```

```{r}
train %>%
  mutate(remodel_flag = ifelse(YearBuilt == YearRemodAdd, "N", "Y")) %>%
  ggplot(aes(x = remodel_flag, y = psf, fill = remodel_flag)) +
  geom_boxplot()
```

```{r}
train %>%
  mutate(remodel_flag = ifelse(YearBuilt == YearRemodAdd, "N", "Y")) %>%
  filter(remodel_flag == "Y") %>%
  ggplot(aes(x = YearRemodAdd, y = psf)) +
  geom_jitter(color = "red", alpha = 0.3)
```

```{r}
train %>%
  mutate(remodel_flag = ifelse(YearBuilt == YearRemodAdd, "N", "Y")) %>%
  filter(remodel_flag == "Y") %>%
  ggplot(aes(x = YearRemodAdd, y = psf, fill = YearBuilt)) +
    geom_bar(stat = "identity")
# Conclusion : What happended in 1950?

```

```{r}
#RoofStyle: Type of roof
train %>%
  group_by(RoofStyle) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
# Conclusion : Pass. Nothing to differentiate between top 2 values
```

```{r}
#RoofMatl: Roof material
train %>%
  group_by(RoofMatl) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
#Conclusion : Again most of the values belong to one category only 
```

```{r}
#Exterior1st: Exterior covering on house
train %>%
  group_by(Exterior1st) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = Exterior1st, y = psf, fill =  Exterior1st)) +
  geom_boxplot() +
  theme(legend.position = "none") +
  coord_flip()
#Conclusion : Interestign feature
```

```{r}
#Exterior2nd: Exterior covering on house (if more than one material)
train %>%
  group_by(Exterior2nd) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
train %>%
  group_by(Exterior1st, Exterior2nd) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
# Conclusion : Exterior 2nd is equal to 1st if both exterior are same.
```

```{r}
# MasVnrType: Masonry veneer type
train %>%
  group_by(MasVnrType) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = MasVnrType, y = psf, fill =  MasVnrType)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Need to replace null values with none
```

```{r}
#MasVnrArea: Masonry veneer area in square feet
train %>%
  ggplot(aes(x = MasVnrArea)) +
  geom_histogram(binwidth = 50)
```

```{r}
train %>%
  ggplot(aes(x = MasVnrArea, y = psf)) +
  geom_jitter(color = "red", alpha = 0.3) +
  geom_smooth(methold = "lm")
# Conclusion : most of the value are 0
```

```{r}
# ExterQual: Evaluates the quality of the material on the exterior 
train %>%
  group_by(ExterQual) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = ExterQual, y = psf, fill =  ExterQual)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclusion : Excellent feature. Clear distinction between top 2 values - Good and Average
```

```{r}
# ExterCond: Evaluates the present condition of the material on the exterior
train %>%
  group_by(ExterCond) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = ExterCond, y = psf, fill =  ExterCond)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclusion : Nope.
```

```{r}
# Foundation: Type of foundation
train %>%
  group_by(Foundation) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = Foundation, y = psf, fill =  Foundation)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclusion : Nice One! Clear distinction between top 2 values
```

```{r}
# BsmtQual: Evaluates the height of the basement
train %>%
  group_by(BsmtQual) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = BsmtQual, y = psf, fill =  BsmtQual)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclusion : Again superb picture. Nice distinction between top 3 values 
```

```{r}
# BsmtCond: Evaluates the general condition of the basement
train %>%
  group_by(BsmtCond) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
# Conclusion : Not of my liking ..Leave it
```

```{r}
# BsmtExposure: Refers to walkout or garden level walls
train %>%
  group_by(BsmtExposure) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = BsmtExposure, y = psf, fill =  BsmtExposure)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclustion : No clear distinction
```

```{r}
# BsmtFinType1: Rating of basement finished area
train %>%
  group_by(BsmtFinType1) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
```

```{r}
ggplot(train, aes(x = BsmtFinType1, y = psf, fill =  BsmtFinType1)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclusion : Not bad
```

```{r}
# BsmtFinSF1: Type 1 finished square feet
ggplot(train, aes(x = BsmtFinSF1)) +
  geom_histogram(alpha = 0.5, fill = "red") 
```

```{r}
train %>%
  ggplot(aes(x = BsmtFinSF1, y = psf)) +
  geom_jitter(color = "red", alpha = 0.3) +
  geom_smooth(methold = "lm")
# Conclustion : Not good feature
```

```{r}
# Conclusion : BsmtFinType2: Rating of basement finished area (if multiple types)
train %>%
  group_by(BsmtFinType2) %>%
  summarise(count = n(),
            avg = mean(psf),
            median = median(psf))
# Conclusion : Not so good
```

```{r}
# BsmtFinSF2: Type 2 finished square feet
train %>%
  ggplot(aes(x = BsmtFinSF2, y = psf)) +
  geom_jitter(color = "red", alpha = 0.3) +
  geom_smooth(methold = "lm")

```

```{r}
train %>%
  mutate(bsmt2Flag = ifelse(BsmtFinSF2 == 0, "N", "Y")) %>%
  ggplot(aes(x = bsmt2Flag, y = psf, fill = bsmt2Flag)) +
  geom_boxplot() +
  theme(legend.position = "none")
# Conclusion : most of values are 0. and no co-relation for non zero values
```





Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
